spring:
  datasource:
    url: jdbc:postgresql://172.20.8.28:5432/secure_wallet
    username: tr4fka
    password: 22102004d
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
jwt:
  secret: your-super-secret-key-that-is-long-and-secure
